server:
  port: 8207
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.75.133:3306/gmall_product
  redis:
    host: 192.168.75.133
    port: 6389
  zipkin:
    base-url: http://192.168.75.133:9411
  rabbitmq:
    host: 192.168.75.133
    port: 5672
    username: guest
    password: guest